README.md
The 'singleSignOnService' in service provider is called 'assertionConsumerService'
=> rename property in documentation

examples/sp1/routes/sso.js
Currently the SP1 example/workflow doesn't work as described in the readme, this is due to the changes made for the 'onelogin'. Added this little questionmark will make sure both work, the paramater is available when used, but otherwise not skipping the route whenever it doesn't.
=> Update SP1 to work

lib/Utility.js
When the X509 certificate was read an extra `undefined` was appended to the data.
The last `.replace()` was missing the substitution string parameter, which was defaulted to `undefined`.
=> Fix X509 Certificate reading error

lib/SPMetadata.js, test/index.js
`SPMetadata.getAssertionConsumerService()` was returning incorrectly when there was only a single binding.
=> SPMetadata.getAssertionConsumerService failure

lib/SPMetadata.js
Before this changes index value was 0 in any AssertionConsumerService tags
```xml
<AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
Location="/sso/acs"/>
<AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
Location="/sso/acs"/>
```
=> Fixed sp-metadata assertion tag indexing

.gitignore, examples/idp/routes/sso.js, examples/sp1/routes/sso.js, examples/sp2/routes/sso.js, src/binding-post.ts, src/entity-idp.ts, src/entity-sp.ts, src/entity.ts, src/libsaml.ts
This PR replaces the callbacks with promises where it makes sense + updates the examples accordingly
Internally it makes use of typescript's async/await features at some places.
The remaining callbacks are for the custom templates, these can remain callbacks and don't need the `(error,result)` signature, since they're not asynchronous callbacks.
Here and there I just added an `any` return type to make compilation work. It might be better to define result interfaces, but that could be done in a future PR.
=> Promisify (+ async/await)

examples/idp/routes/sso.js, examples/sp1/routes/sso.js, examples/sp2/routes/sso.js, src/binding-post.ts, src/binding-redirect.ts, src/entity-idp.ts, src/entity-sp.ts, src/entity.ts, src/libsaml.ts, src/metadata-idp.ts, src/metadata-sp.ts, src/metadata.ts, src/utility.ts, test/index.ts
This allows the user to pass in buffers and strings instead of file paths.
Advantages are more flexibility, e.g.:
- User can decide whether to read files synchronous or asynchronous
- User can pass in XML and Certificates/Keys that are not stored in files. E.g. coming from a database, fetched from a url, ...
Disadvantage: to keep the library simple, I removed the functionality that read the files, but reading a file is so easy in node, that this is a small cost. It could be re-added, but I didn't really see the point, it only adds complexity to the library with little benefit for the user.
=> Pass in raw strings/buffers for metadata and certificates

src/entity-idp.ts, src/entity-sp.ts, src/entity.ts, src/metadata-idp.ts, src/metadata-sp.ts, src/utility.ts, tsconfig.json
In https://github.com/tngan/express-saml2/issues/51 it was decided to only support latest node and node LTS.
That makes the current oldest supported version node 4, which has native support (http://node.green/) for some of the functions that were used from lodash. This PR replaces those functions with their native version.
=> Use native ES2015 features supported by node 4 LTS

package.json, postinstall.js
Do not run post install hook, which installs the pre-commit git hook if we're not running from a git clone (otherwise errors during npm install).
=> Fix post install

package.json
v2 `package.json` main was still referring to v1 location.
=> Fix index file reference

src/metadata.ts
Some federated IDP's metadata contains a set of entity descriptors (e.g. https://shib.kuleuven.be/download/metadata/metadata-kuleuven.xml ) even with a mix of IDP and SP descriptors.
Although this is valid SAML metadata, this library should be fed exactly 1 entity descriptor.
This is an extra check that throws an error when this is not the case
=> Add extra check on metadata

src/binding-post.ts, src/entity-idp.ts, src/entity.ts, src/urn.ts, test/flow.ts
Added configurations for the signing order ('sign-then-encrypt' and 'encrypt-then-sign'). I, also,  added a test case. They were all passing, before 2.0.1 bump.  I, also, deployed this to my container and verified it worked with OKTA with a signed and encrypted assertion Login Response.
Used the below configuration on my SP-side to initialize IDP with new config option:
idp = IdentityProvider({
metadata: fs.readFileSync(.....idpFile)),
isAssertionEncrypted: true,
messageSigningOrder: 'encrypt-then-sign'
});
=> [feature: add support for configuration of signing order [refs:issue 89]

src/libsaml.ts, test/flow.ts
Fix for https://github.com/tngan/samlify/issues/113
This makes sure the signature's X509 cert is used to compare with what is in meta-data, by ensuring the x509 cert is found within the signature node and not the entire SAMLResponse document.
I did not write a negative test, but you can "remove" the "dot" (.) in libsaml and "send login response with encrypted non-signed assertion with EncryptThenSign and parse it" test will fail.
=> Fix: xpath select for validating signature [Fixes:113]

src/entity-sp.ts
@tngan Not sure if this is the way to go, but It seems that `samlify` needs the `SessionIndex` to start a logout request. However, is not parse during the loginResponse. So, this PRs adds it.
=> Parses SessionIndex in the login response

README.md
Should be `yarn global add typescript`?
=> Fix yarn install guide for typescript

docs/advance.md, docs/encrypted-saml-response.md
Just a few minor grammar errors in the documentation that needed fixing.
=> Minor grammar fixes in documentation

src/entity.ts
The `notBefore` and `notOnOrAfter` are UTC while `now` is the local date. This way the comparison can not work.
The added variables should fix this.
(ref: https://praveenlobo.com/blog/how-to-convert-javascript-local-date-to-utc-and-utc-to-local-date/)
=> Fixed verifyTime not working with local time

src/binding-redirect.ts, src/libsaml.ts, test/flow.ts
Updating logic of `customReplaceTag` to accept tags created by the entity.
callback function for `createLogoutRequest` would look like this
```
(template, tags) => {
const customTags = {
SessionIndex: ''
}
return customReplaceTagsByValue(template, { ...tags, ...customTags});
}
```
`customReplaceTagsByValue` being a function that returns { context, id } and can be very similar to `libsaml.replaceTagsByValue`
PR associated with #196
=> logoutRequestRedirectURL now replaces required and custom tags

src/libsaml.ts
Related to the change in issue 129 - this change avoids having to change the process working directory by specifying the "cwd" for the validator library
=> xsd-schema-validator - Specify schema directory instead of changing process directory

schemas/XMLSchema.dtd, schemas/datatypes.dtd, schemas/xenc-schema.xsd, schemas/xmldsig-core-schema.xsd
By storing local copies of the dtd files and changing references
to refer to them, the samlify library no longer makes network requests
while validating XML.
Fixes https://github.com/nikku/node-xsd-schema-validator/issues/17
Addresses https://stackoverflow.com/questions/52392690/xsd-schema-validator-fails-to-validate-samlify-xml
=> Allow validating SAML responses without network connection

src/libsaml.ts
samlify stopped validate a cert because of this condition - I am sure that is a mistake.
=> Validate cert when there is only one

.travis.yml, Makefile, README.md, package.json, test/flow.ts, yarn.lock
this allows installation to succeed even if javac is not present
also remove redundant 'npm install's from preinstall script
relates to issue #258
=> add all validators as optional dependencies in package.json

package.json, src/schema-validator.ts
Using  version 2.5.0 we were having problems with java causing ENOMEM, libxml-xsd won't compile against node 10.15 so we tried using node-xmllint for schema validation. The server would crash unexpectedly without a stack trace.  So, I have been testing with validate-with-xmllint, which uses native OS xmllint (via libxml2-utils package for debian)..instead of the node-xmllint which is an Emscripten port of xmllint.    node-xmllint hasn't been updated in 3 years and libxml-xsd hasn't been updated in 3 years either.    Validate-with-xmllint is typescript, and it's only 2 months old but the best part is that its a very lightweight wrapper around the system xmllint so there is very little code to maintain.    The xmllint on the system is maintained by the Linux OS developers and the GNOME …
=> use native xmllint for schema validation on linux

src/libsaml.ts
I was getting a falsey condition on what seemed to be identical strings. I noticed trailing spaces in the certs that were being compared.
I added a trim method in the "ERROR_UNMATCH_CERTIFICATE_DECLARATION_IN_METADATA" check.
=> Trim unneeded spaces that may make their way in from the metadata

src/libsaml.ts, test/index.ts
**Without** the optional dependency libxml-mt installed. If these two attributes are not provided the xml validator will complain about xml namespace problem. So we'd better add these two attribute to saml attribute value as optional attributes.
```javascript
let idp = IdentityProvider({
metadata:IdPMetadata,
encPrivateKey:encPrivateKey,
privateKey:privateKey,
encPrivateKeyPass:encPrivateKeyPass,
privateKeyPass:privateKeyPass,
loginResponseTemplate: {
context:
'<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="{ID}" Version="2.0" IssueInstant="{IssueInstant}" Destination="{Destination}"><saml:Issuer>{Issuer}</saml:Issuer><samlp:Status><samlp:StatusCode Value="{StatusCode}"/></samlp:Status><saml:Assertion …
```
=> fix: add xmlns:xs and nmlns:xsi attribute

src/binding-post.ts, src/binding-redirect.ts, src/libsaml.ts
1. Remove SPNameAualifier attributes from `defaultLogoutRequestTemplate`
2. Change logout nameId format to take nameIDFormat from entity settings.
=> Logout request template and Logout NameID format consistency

src/entity.ts
Right now if SP metadata is not specifying `NameIDFormat` and `ServiceProvider` object will have `nameIDFormat` set to null even though `ServiceProvider` was initialized with a value.
Proposal is to fallback to `ServiceProvider` settings if metadata is not specifying.
=> Fallback to object settings if metadata is not specifying NameIDFormat

src/extractor.ts
I think this is a typo in the parameter name.
=> Fixed typo in loginResponseFields

src/types.ts
It should be possible to set the `requestSignatureAlgorithm` setting and overwrite the default value. As far as I can see this is just a problem with the `ServiceProviderSettings` type.
=> Add missing property to sp settings type

@types/xml-encryption.d.ts, package.json, src/libsaml.ts, yarn.lock
This fixes #355 by using the latest version of `xml-encryption` instead of `@authenio/xml-encryption`. I would have updated the scoped package instead, but I couldn't find a repository for it, and the npm package just points back to `xml-encryption`.
I've run tests and confirmed that all tests pass with the update. This resolves the issue of samlify not playing nice with applications that use webpack (or other bundlers). 
@tngan I'm happy to pay a bounty to get this merged and released. This is a major blocker for my organization.
=> fix: use latest version of xml-encryption

src/extractor.ts
When a node in xml metadata is empty, for example
``` 
<md:KeyDescriptor use="signing">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate></ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:KeyDescriptor use="encryption">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate></ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
```
The piece of code below throwing this error `TypeError: Cannot read property 'nodeValue' of null` at `samlify/build/src/extractor.js:347:41`
```        
if (attributes.length === 0) {
var attributeValue = null;
var node = xpath_1.select(baseXPath, targetDoc);
if (node.length === 1) {
var fullPath = "string(" + baseXPath + attributeXPath + ")";
attributeValue = xpath_1.select(fullPath, targetDoc);
}
if (node.length > 1) { …
```
=> Filter out empty node when extracting attributes from xml metadata

docs/idp-configuration.md, src/binding-redirect.ts, src/binding-simplesign.ts, src/entity-idp.ts, src/entity-sp.ts, src/entity.ts, src/flow.ts, src/libsaml.ts, src/urn.ts, test/flow.ts, test/misc/idpmeta.xml, test/misc/idpmeta_nosign.xml, test/misc/idpmeta_onelogoutservice.xml, test/misc/idpmeta_share_cert.xml, test/misc/spmeta.xml, test/misc/spmeta_noassertsign.xml, test/misc/spmeta_noauthnsign.xml
This pull request contains the following enhancements and fixes:
- Support SAML response over HTTP-REDIRECT binding,
- Add Login Request/Response over HTTP-POST SimpleSign binding,
- Enable clock drifts parameters from IDP setting,
- Fix NameIDFormat extraction from IDP metadata.
- Add AttributeStatementTemplate, AttributeTemplate and LoginResponseAdditionalTemplates interfaces
- Modify attributeStatementBuilder
This PR also brings a commit that fixes the issue #382 .
=> Enhance SAML protocol support

src/libsaml.ts
This seems to be a bug where the method sets up a default array of transformations when none is passed in the options but then this code ignores the defaults and uses the ones from the options passed which could be undefined.  The addReference then possibly passes an undefined transformations which xml-crypto library only adds 'http://www.w3.org/2001/10/xml-exc-c14n#' instead of 'http://www.w3.org/2001/10/xml-exc-c14n#' and 'http://www.w3.org/2000/09/xmldsig#enveloped-signature' defined in this codebase's constructSAMLSignature.
=> Fixes issue with SAMLSignature method not using default transformations

src/utility.ts
This is something that Okta now does!
=> Makes normalizeCerString() handle inserted tabs (fixes issue with Okta)

src/api.ts, src/binding-post.ts, src/binding-simplesign.ts, src/entity-idp.ts, src/flow.ts, src/libsaml.ts, src/metadata-idp.ts, src/metadata-sp.ts, src/metadata.ts, src/types.ts, src/utility.ts, test/index.ts
Brings the `signingCert` and `encryptCert` args on the entities up to parity with raw metadata when multiple KeyDescriptors are desired for each use.
@tngan
=> Allow arrays of certs to be provided 

src/extractor.ts, test/flow.ts
Feature Request in PR form.
As SP/IdP, we have to identify session with SessionIndex when received LoginRequest.
So it is convenient to extract it with parseLogoutRequest.
=> extract sessionIndex from LogoutRequest

src/libsaml.ts, test/flow.ts, test/index.ts
`@xmldom/xmldom` 0.8.6 included: "fix: Properly check nodes before replacement."
https://github.com/xmldom/xmldom/pull/457
Which caused the `.replaceChild` calls in `encryptAssertion` and `decryptAssertion` to error with:
> "Not found: child not in parent"
The root cause is a subtle difference in `@xmldom/xmldom` `Document` vs `Element` instances.
The previous code was asking xmldom to replace an element from a top-level Document with another top-level Document. The patch to xmldom 0.8.6 started the enforcement of `.replaceChild` being passed `Nodes` who share a common parent Node.
e.g. in the case of `encryptAssertion`: `doc.replaceChild(encryptAssertionNode, rawAssertionNode)`.
It's important to distinguish that neither `doc` nor `encryptAssertionNode` are `Element` nodes, but instead …
=> Fix encryption for @xmldom/xmldom 0.8.6 upgrade

index.ts, src/api.ts, src/extractor.ts, src/libsaml.ts
Decided to have a go at #534, tried to do it by adding `@xmldom/xmldom` parser options to the context, and using it when creating parser instances
closes #534
=> Add dom parser options for context customization

docs/sp-configuration.md
- credit to https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf for language
- option was made configurable in https://github.com/tngan/samlify/pull/363
- noticed while looking into [reported issue](https://github.com/tngan/samlify/issues/538) that docs needed updating
=> Adds `allowCreate` documentation
